
services:
  app:
    build: .
    image: web
    ports:
      - "8010:8010"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: nastya
      DB_PASSWORD: nastya
      DB_NAME: mydb
      DATABASE_URL: "postgresql://nastya:nastya@db:5432/mydb"
      MONGO_URI: "mongodb://admin:password@mongodb:27017"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      mongodb: 
        condition: service_healthy
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: postgres_container_web
    environment:
      POSTGRES_USER: nastya
      POSTGRES_PASSWORD: nastya
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nastya -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "-u", "admin", "-p", "password", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - my_network
    restart: unless-stopped 

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/var/www/static
      - ./docs:/var/www/docs
      - ./management:/var/www/management
    depends_on:
      - app
    networks:
      - my_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: travelguide-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@travelguide.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - my_network

volumes:
  postgres_data:
  mongodb_data:
  pgadmin-data:

networks:
  my_network:
    driver: bridge