# worker_processes 1;

# events {
#     worker_connections 1024;
# }

# http {
#     include       /etc/nginx/mime.types;
#     default_type  application/octet-stream;

#     sendfile on;
#     keepalive_timeout 65;

#     log_format main '$remote_addr - $remote_user [$time_local] "$request" '
#                     '$status $body_bytes_sent "$http_referer" '
#                     '"$http_user_agent" "$http_x_forwarded_for"';

#     access_log /var/log/nginx/access.log main;
#     error_log /var/log/nginx/error.log warn;

#     # ------------------------
#     # upstream для GET/READ и WRITE
#     # ------------------------
#     upstream backend_get {
#         server app_main:8010 weight=2;
#         server app_read1:8010 weight=1;
#         server app_read2:8010 weight=1;
#     }

#     upstream backend_write {
#         server app_main:8010;
#     }

#     # ------------------------
#     # Включаем старые include, например /management
#     # ------------------------
#     include /etc/nginx/conf.d/*.conf;

#     # ------------------------
#     # Основной сервер
#     # ------------------------
#     server {
#         listen 80;

#         # API v1
#         location /api/v1/ {
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;

#             # Все, кроме GET → backend_write
#             limit_except GET {
#                 proxy_pass http://backend_write;
#             }

#             # GET → backend_get
#             proxy_pass http://backend_get;
#         }

#         # API v2
#         location /api/v2/ {
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;

#             limit_except GET {
#                 proxy_pass http://backend_write;
#             }

#             proxy_pass http://backend_get;
#         }

#         # Management (статический интерфейс)
#         location /management/ {
#             root /usr/share/nginx/html;
#             index index.html;
#         }

#         # Любые другие запросы → 404
#         location / {
#             return 404;
#         }
#     }
# }
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /usr/local/openresty/nginx/conf/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

     # -------------------------------
    # GZIP-сжатие
    # -------------------------------
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xhtml+xml
        application/rss+xml
        application/atom+xml
        font/ttf
        font/otf
        image/svg+xml;

    # -------------------------------
    # Кеширование статики
    # -------------------------------
    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m use_temp_path=off;
    
    # --------- Балансировка ---------
    upstream backend_get {
        server gateway_main:8010 weight=2;
        server gateway_read1:8010 weight=1;
        server gateway_read2:8010 weight=1;
    }

    upstream backend_write {
        server gateway_main:8010;
    }

    include /etc/nginx/conf.d/*.conf;
}