# Allow local connections
local all all trust

# Allow all connections inside Docker network
host all all 0.0.0.0/0 md5

# Allow replication from any container in docker network
host replication replica_user 0.0.0.0/0 md5